python_binary(
  name='dash-scratch',
  source='app.py',
  dependencies = [
    ':dash',
    ':dash-core-components',
    ':dash-html-components',
    ':pandas',
    ':plotly',
  ],
)

python_requirements(
  requirements_relpath='../requirements.txt'
)
